### ISSUE TITLE
fatal error: keystone/keystone.h: No such file or directory

### ISSUE THREAD

**Issue by NotoriousRebel** [EgeBalci/sgn#1]
This project seems very interesting and I would like to play around with it; however, I am having trouble compiling it. 
![image](https://user-images.githubusercontent.com/36310667/82829067-683c3480-9e80-11ea-9de6-4d03eb5f7359.png)

**Comment by NotoriousRebel** [comment]
I did this before I attempted to build the project ```sudo apt-get install libcapstone-dev```

**Comment by EgeBalci** [comment]
I changed the requirements section sorry for the inconvenience.  Installation of keystone engine can be a little tricky some time check [here](https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE.md) for library installation guide`(don't forget to compile as .lib)`.  I am looking for a way to remove all external dependencies for future releases.

**Comment by NotoriousRebel** [comment]
Thank you for the quick response installing keystone correctly did the trick.
