### ISSUE TITLE
"go get" is not recommended to use

### ISSUE THREAD

**Issue by Bit-flipper** [EgeBalci/sgn#11]
Hi,
the Go team suggests that we should use "go install github.com/example/example.git@latest" to download+compile latest package because "go get" will not support compile in the future.

See:https://go.dev/doc/go-get-install-deprecation

**Comment by EgeBalci** [comment]
Hi, yes indeed. But SGN is also a package, If you want to use it as a library you should use `go get`. If you only want the tool you can use `go install` as you said.
